string = input("Digite uma frase: ")
print("É alfebético ?", string.isalpha())
print("É numérico ?", string.isnumeric())
print("É alfanumérico ?", string.isalnum())
print("Está em maiúsculas ?", string.isupper())
print("Está em minúsculas ?", string.islower())
print("Está começando com letra maiúscula (capitalizado) ?", string.istitle())
print("Possui apenas espaços? ", string.isspace())
